esphome:
  name: esphome-web-efd060
  friendly_name: Osaka Bed

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "<KEY SHOULD BE SUPPLIED BY HOME ASSISTANT>"

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

esp32_ble_tracker:

ble_client:
  - mac_address: "<OSAKA TV BED MAC ADDRESS>"
    id: my_ble_client

cover:
  - platform: template
    name: "TV Lift"
    id: "osaka_tv_bed"
    has_position: false
    assumed_state: false
    open_action:
      - ble_client.ble_write:
          id: my_ble_client
          service_uuid: 0000ae00-0000-1000-8000-00805f9b34fb
          characteristic_uuid: 0000ae03-0000-1000-8000-00805f9b34fb
          value: [0x55, 0xAA, 0xF5, 0x0A, 0xF3, 0x0C, 0xFE]  # Lift up command
      - cover.template.publish:
          id: osaka_tv_bed
          current_operation: OPENING
      - delay: 20s
      - ble_client.ble_write:
          id: my_ble_client
          service_uuid: 0000ae00-0000-1000-8000-00805f9b34fb
          characteristic_uuid: 0000ae03-0000-1000-8000-00805f9b34fb
          value: [0x55, 0xAA, 0xF5, 0x0A, 0xF0, 0x0F, 0xFE]  # Lift stop command
      - delay: 0.1s # The official app waits 100ms and writes the stop command again
      - ble_client.ble_write:
          id: my_ble_client
          service_uuid: 0000ae00-0000-1000-8000-00805f9b34fb
          characteristic_uuid: 0000ae03-0000-1000-8000-00805f9b34fb
          value: [0x55, 0xAA, 0xF5, 0x0A, 0xF0, 0x0F, 0xFE]  # Lift stop command
      - cover.template.publish:
          id: osaka_tv_bed
          state: OPEN
          current_operation: IDLE
    close_action:
      - ble_client.ble_write:
          id: my_ble_client
          service_uuid: 0000ae00-0000-1000-8000-00805f9b34fb
          characteristic_uuid: 0000ae03-0000-1000-8000-00805f9b34fb
          value: [0x55, 0xAA, 0xF5, 0x0A, 0xF2, 0x0D, 0xFE]  # Lift down command
      - delay: 0.1s
      - cover.template.publish:
          id: osaka_tv_bed
          current_operation: CLOSING
      - delay: 15s
      - ble_client.ble_write:
          id: my_ble_client
          service_uuid: 0000ae00-0000-1000-8000-00805f9b34fb
          characteristic_uuid: 0000ae03-0000-1000-8000-00805f9b34fb
          value: [0x55, 0xAA, 0xF5, 0x0A, 0xF0, 0x0F, 0xFE]  # Lift stop command
      - delay: 0.1s # The official app waits 100ms and writes the stop command again
      - ble_client.ble_write:
          id: my_ble_client
          service_uuid: 0000ae00-0000-1000-8000-00805f9b34fb
          characteristic_uuid: 0000ae03-0000-1000-8000-00805f9b34fb
          value: [0x55, 0xAA, 0xF5, 0x0A, 0xF0, 0x0F, 0xFE]  # Lift stop command
      - cover.template.publish:
          id: osaka_tv_bed
          state: CLOSED
          current_operation: IDLE
    stop_action:
      - ble_client.ble_write:
          id: my_ble_client
          service_uuid: 0000ae00-0000-1000-8000-00805f9b34fb
          characteristic_uuid: 0000ae03-0000-1000-8000-00805f9b34fb
          value: [0x55, 0xAA, 0xF5, 0x0A, 0xF0, 0x0F, 0xFE]  # Lift stop command
      - delay: 0.1s # The official app waits 100ms and writes the stop command again
      - ble_client.ble_write:
          id: my_ble_client
          service_uuid: 0000ae00-0000-1000-8000-00805f9b34fb
          characteristic_uuid: 0000ae03-0000-1000-8000-00805f9b34fb
          value: [0x55, 0xAA, 0xF5, 0x0A, 0xF0, 0x0F, 0xFE]  # Lift stop command
      - cover.template.publish:
          id: osaka_tv_bed
          current_operation: IDLE
    
